### ISSUE TITLE
[!] Error : can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by utkarsh-nan** [Technowlogy-Pushpender/technowlogger#3]
[!] Error : can only concatenate str (not "NoneType") to str

**Comment by Technowlogy-Pushpender** [comment]
I just forget to update the "How to use" Section of Readme

As I added new argument to technowlogger i.e. **  --icon **
which takes icon path so that an icon to evil file can be assigned.

few icons are also available in **icon folder** which can be used like this  ** --icon icon/pdf.ico **

You might not have given --icon argument

**Comment by Technowlogy-Pushpender** [comment]
Just Edited technowgen.py [Daemon Generator]

Add a Check that if icon is not defined.
Prompt will ask for the icon path, if then also leave blank, add icon/exe.ico as Default icon
