### ISSUE TITLE
Problem sending logs.

### ISSUE THREAD

**Issue by ImOnlyUser** [Technowlogy-Pushpender/technowlogger#6]
During 1 start of payload, the program sends logs. Send a screen from the desktop and a log that the script has been started. The script doesn't send anything. (Standard script setting)

**Comment by Technowlogy-Pushpender** [comment]
Edit line 116 and 119 in technowgen.py,

Just remove  this word from line  **--noconsole**
And then create a fresh payload, this time the payload will not going to work in background, It will run CMD window in front of user

Just notice ERROR in your payload, error could be a missing dependencies etc

Send detected error to us, so that we can look further.

Scripts works absolutely fine in my case

**Comment by glinskicwb1988** [comment]
Same error here. Keylogger sends first message and one screenshot, then stops working.

Tried to remove all "--noconsole" from the main py file, but now the console window just open and closes not showing any errors.

**Comment by Technowlogy-Pushpender** [comment]
You might running the payload by double click, run in command prompt in order to see the error

**Comment by Technowlogy-Pushpender** [comment]
Also try to re download the tool

**Comment by ImOnlyUser** [comment]
Despite the upgrade, the script still does not work. There is the same problem with sending logs. Removing --noconsole except for the script from the front does not change anything.

**Comment by ImOnlyUser** [comment]
The problem lies with the code side. You have to solve this problem because payload is not working properly.

**Comment by glinskicwb1988** [comment]
> You might running the payload by double click, run in command prompt in order to see the error

Thank you for your input.

Tried to run using the cmd line.

Result:

"No module named win32event"

And 

5800 Failed to execute script key.

Hope it helps.

**Comment by glinskicwb1988** [comment]
Installed pywin32, solved the problem. But the problem persists. 

Now, if I try to see the error in console, I only see a message like "Keylogger already running"

**Comment by Technowlogy-Pushpender** [comment]
Check this path for virus : `C:\Users\USERNAME\AppData\Roaming`
`"Keylogger already running"` is not a error, I added a functionality in keylogger that prohibits multiple instance, 

If this feature is not there then you could get multiple mails at a same time, as same keylogger might be running instance on on system.

@ImOnlyUser script working file, but then also i just added a `try except conditions in Log Distinguished function`

Please Try again,

**Comment by Technowlogy-Pushpender** [comment]
Video Proof, which proofs that script works 
[Video Proof.zip](https://github.com/Technowlogy-Pushpender/technowlogger/files/3939361/Video.Proof.zip)
Only **receive test** is shown in this video [2.20 min video length]

**Comment by glinskicwb1988** [comment]
I think the problem must be Windows 10 then.

Only now I saw you tested it on windows 8.1.

**Comment by ImOnlyUser** [comment]
@Technowlogy-Pushpender  Okay, what should I do to make everything work properly?

**Comment by ImOnlyUser** [comment]
@Technowlogy-Pushpender  Okay, what should I do to make everything work properly?

**Comment by Technowlogy-Pushpender** [comment]
I also tested the script on my friend's PC which is Using windows 10.

There is no issue of compatibility,  You might have not installed All required Modules on your system.
Show me the error, so that i can troubleshoot it

**Comment by glinskicwb1988** [comment]
Hello, @Technowlogy-Pushpender 

- Installed all 7 modules required (mss==4.0.3, pynput==1.4.4, essential_generators==0.9.2, python-xlib==0.25, six==1.12.0, PyInstaller, pywin32)

- Compiled the program removing the two lines of "--noconsole" on the keygen file using a windows 10 x64.

- Compilation success:

`[?] These info above are correct? (y/n) : y

[*] Checking Dependencies...
[+] All Dependencies are Installed on this system ;)


[*] Generating Please wait for a while...


[*] Encrypting Source Codes...
[+] Operation Completed Successfully!


95 INFO: PyInstaller: 4.0.dev0+9dd34bdfba
95 INFO: Python: 3.7.5
96 INFO: Platform: Windows-10-10.0.18362-SP0
97 INFO: wrote c:\log\key.spec
98 INFO: UPX is not available.
102 INFO: Extending PYTHONPATH with paths
['c:\\log', 'c:\\log']
103 INFO: checking Analysis
103 INFO: Building Analysis because Analysis-00.toc is non existent
104 INFO: Initializing module dependency graph...
107 INFO: Caching module graph hooks...
129 INFO: Analyzing base_library.zip ...
3711 INFO: Caching module dependency graph...
3788 INFO: running Analysis Analysis-00.toc
3809 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\fabio\AppData\Local\Programs\Python\Python37\python.exe
3898 INFO: Analyzing c:\log\key
3902 INFO: Analyzing hidden import 'win32event'
3903 INFO: Analyzing hidden import 'winerror'
3968 INFO: Analyzing hidden import 'win32api'
3969 INFO: Analyzing hidden import 'pynput.keyboard'
4101 INFO: Processing pre-safe import module hook   six.moves
4854 INFO: Analyzing hidden import 'keylogger'
5041 INFO: Processing module hooks...
5041 INFO: Loading module hook "hook-encodings.py"...
5108 INFO: Loading module hook "hook-pydoc.py"...
5109 INFO: Loading module hook "hook-Xlib.py"...
5441 INFO: Loading module hook "hook-xml.py"...
5685 INFO: Looking for ctypes DLLs
5702 INFO: Analyzing run-time hooks ...
5707 INFO: Looking for dynamic libraries
5931 INFO: Looking for eggs
5931 INFO: Using Python library C:\Users\fabio\AppData\Local\Programs\Python\Python37\python37.dll
5932 INFO: Found binding redirects:
[]
5934 INFO: Warnings written to c:\log\build\key\warn-key.txt
5970 INFO: Graph cross-reference written to c:\log\build\key\xref-key.html
5979 INFO: checking PYZ
5979 INFO: Building PYZ because PYZ-00.toc is non existent
5979 INFO: Building PYZ (ZlibArchive) c:\log\build\key\PYZ-00.pyz
6606 INFO: Building PYZ (ZlibArchive) c:\log\build\key\PYZ-00.pyz completed successfully.
6619 INFO: checking PKG
6619 INFO: Building PKG because PKG-00.toc is non existent
6619 INFO: Building PKG (CArchive) PKG-00.pkg
8091 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
8092 INFO: Bootloader C:\Users\fabio\AppData\Local\Programs\Python\Python37\lib\site-packages\pyinstaller-4.0.dev0+9dd34bdfba-py3.7.egg\PyInstaller\bootloader\Windows-64bit\run.exe
8093 INFO: checking EXE
8093 INFO: Building EXE because EXE-00.toc is non existent
8094 INFO: Building EXE from EXE-00.toc
8139 INFO: Copying icons from ['icon\\exe.ico']
8184 INFO: Writing RT_GROUP_ICON 0 resource with 90 bytes
8184 INFO: Writing RT_ICON 1 resource with 744 bytes
8185 INFO: Writing RT_ICON 2 resource with 2216 bytes
8186 INFO: Writing RT_ICON 3 resource with 1384 bytes
8187 INFO: Writing RT_ICON 4 resource with 9640 bytes
8188 INFO: Writing RT_ICON 5 resource with 4264 bytes
8189 INFO: Writing RT_ICON 6 resource with 1128 bytes
8192 INFO: Updating manifest in c:\log\build\key\run.exe.epy75idk
8233 INFO: Updating resource type 24 name 1 language 0
8235 INFO: Appending archive to EXE c:\log\dist\key.exe
8283 INFO: Building EXE from EXE-00.toc completed successfully.

[*] Deleting Junk Files...
[+] Junk Files Removed Successfully!

[+] Generated Successfully!`

- Running the compiled keylogger on a VM of windows 10 x64 pro using command line with admin privilegies:

![image](https://user-images.githubusercontent.com/58521582/70532635-36cfe680-1b36-11ea-9937-37463feb1f15.png)

Translating to english:

"O nome do serviço é inválido" = The name of the service is invalid. I think the keylogger tried to end a AV service that didn't exist.

The other line: "Para mais ajuda digite helpmsg 2185." = For more help type helpmsg 2185

Then the last line "A operação foi concluída com êxito" = The operation ended with success.

![image](https://user-images.githubusercontent.com/58521582/70532867-9e863180-1b36-11ea-970c-597d7d9527c5.png)

Received the first two emails, one with "Keylogger started on windows 10 system" and the second with a screenshot, but even after typing a lot (see the clock when the capture was made), no more emails.

**Comment by Technowlogy-Pushpender** [comment]
I think the problem is with latest pyinstaller, 
I am using `pyinstaller==3.5`

Try to install this version, hope this helps

**Comment by Technowlogy-Pushpender** [comment]
Also, this result means,

`The operation ended with success.`  That keylogger successfully managed to become persistence on Victim Successfully

**Comment by ImOnlyUser** [comment]
@Technowlogy-Pushpender I have the same problem with sending logs to gmail. I have pyinstaller3.5 and it doesn't help.

**Comment by glinskicwb1988** [comment]
Tried using pyinstaller==3.5, but the problem is still the same.

It's weird, because the program can indeed send the e-mails successfully, takes screenshots, etc..., but for some reason it's not recording the keystrokes or not respecting the intervals to send emails.

Can you tell me which function record the strokes ? Maybe if we try to record to a .txt file first, to see if everything is fine or try to send the txt as a attachment (like the screenshot).

Thank you for your time.

**Comment by Technowlogy-Pushpender** [comment]
@glinskicwb1988  Run **test_key.py** In both the modes [Compiled & Raw] and figure out whats the error

Run it like this : `python test_key.py`

Also Compile it like this: 
`pyinstaller --onefile test_key.py --hidden-import=win32event --hidden-import=winerror --hidden-import=win32api --hidden-import=pynput.keyboard`

After running it, Start typing something,
Result will be displayed on the Command prompt after every 10 seconds

**Comment by glinskicwb1988** [comment]
> @glinskicwb1988 Run **test_key.py** In both the modes [Compiled & Raw] and figure out whats the error
> 
> Run it like this : `python test_key.py`
> 
> Also Compile it like this:
> `pyinstaller --onefile test_key.py --hidden-import=win32event --hidden-import=winerror --hidden-import=win32api --hidden-import=pynput.keyboard`
> 
> After running it, Start typing something,
> Result will be displayed on the Command prompt after every 10 seconds

Hello, @Technowlogy-Pushpender.

Ran both (raw and compiled) and the script recorded the keystrokes perfectly.

**Comment by Technowlogy-Pushpender** [comment]
Hello @glinskicwb1988 

I think the problem is with your pyinstaller, it might not able to import threading module
please  try to add this arugment in `--hidden-import=threading`
in technowgen.py in Line 167, 169, 173, 175

Hope this works, and please inform me if it works
